### ISSUE TITLE
yarn start?

### ISSUE THREAD

**Issue by tfcarlin** [adrianromero/myhelloiot#1]
Hi, I receive an error when attempting to start. Thanks!

~/myhelloiot $ yarn start
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'start'

**Comment by adrianromero** [comment]
Can you please check you have yarn properly installed? 

https://www.npmjs.com/package/yarn

An then please execute before:

`yarn install`

I just changed the README instructions

**Comment by tfcarlin** [comment]
That fixed it; thanks!
