### ISSUE TITLE
Where is the installation pages ? 

### ISSUE THREAD

**Issue by volkanunal** [adrianromero/myhelloiot#2]
> To execute MYHELLOIOT just open your browser and go to [MYHELLOIOT](https://adrianromero.github.io/myhelloiot/). And if you want to install it, in the browser menu select Install application.

I did not find the installation pages in the link.

**Comment by adrianromero** [comment]
For example in Chrome it is in the browser menu:

![Screenshot from 2022-12-16 11-44-37](https://user-images.githubusercontent.com/528700/208082094-c2795f4d-1ddb-4f7f-b743-8222e6f24688.png)
